/* ***** BEGIN LICENSE BLOCK *****
 * Version: GPL 3.0
 *
 * The contents of this file are subject to the General Public License
 * 3.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * Author: Michel Verbraak (info@1st-setup.nl)
 * Website: http://www.1st-setup.nl/
 * email: info@1st-setup.nl
 *
 * This interface can be used to for updates
 *
 * ***** BEGIN LICENSE BLOCK *****/

#include "nsISupports.idl"

[scriptable, uuid(2db8c940-1927-11e2-892e-0800200c9a55)]
interface mivExchangeLoadBalancer : nsISupports
{

  readonly attribute jsval jobList;
	
  void addToQueue(in jsval aJob);

  void clearQueueForCalendar(in AUTF8String aServer, in jsval aCalendar);
  void stopRunningJobsForCalendar(in AUTF8String aServer, in jsval aCalendar);

};
