/* ***** BEGIN LICENSE BLOCK *****
 * Version: GPL 3.0
 *
 * The contents of this file are subject to the General Public License
 * 3.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * Author: Michel Verbraak (info@1st-setup.nl)
 * Website: http://www.1st-setup.nl/
 * email: info@1st-setup.nl
 *
 * This interface can be used to for updates
 *
 * ***** BEGIN LICENSE BLOCK *****/

#include "nsIAuthPrompt2.idl"

[scriptable, uuid(b3ab11c0-20f7-11e2-81c1-0800200c9a66)]
interface mivExchangeAuthPrompt2 : nsIAuthPrompt2
{

	const unsigned long ERR_USER_CANCEL = 1;

	AUTF8String getPassword(in jsval aChannel, in AUTF8String username, in AUTF8String aURL, [optional] in AUTF8String realm, [optional] in boolean alwaysGetPassword,[optional] in boolean useCached);

	boolean getUserCanceled(in AUTF8String aURL);

	void removeUserCanceled(in AUTF8String aURL);

	void removePasswordCache(in AUTF8String aUsername, in AUTF8String aURL);


};
